### ISSUE TITLE
Galeria does not load in Chrome

### ISSUE THREAD

**Issue by abias** [lionel-m/galerie#12]
Hi installed version 2.1.0 of your plugin from the Contao plugin repository into Contao 3.2.13.

When I create a galeria and add it into an article, the galeria is loaded in Firefox/Mac, but does not load in Chrome 32/Mac. Instead, there is an error message:
Fatal error: Theme CSS could not load after 20 sec. Please download the latest theme at http://galleria.io/customer/.

Can you reproduce this problem and tell me what I can do to show the galeria in Chrome?

Thanks,
Alex

**Comment by TylerWilcock** [comment]
I'm still having this problem.
