### ISSUE TITLE
Non Admin: Adding a new pic: Error

### ISSUE THREAD

**Issue by mathContao** [lionel-m/galerie#15]
galerie V2.2.0 Build 6 (= newest Version). Contao 3.2.15/16

Non-admin-user cannot add new pictures to a gallery (red marked green plus-buttons). 
First green plus-button works (grey row [title, width, height], right corner).

Admin-User works fine.

![0-galerie](https://cloud.githubusercontent.com/assets/1645099/5516156/74efe352-888d-11e4-896e-c079af44e936.png)
![1-error-message](https://cloud.githubusercontent.com/assets/1645099/5516155/74eb7a06-888d-11e4-8e87-56680c65dd48.png)

![settings-1-galleria-permissions](https://cloud.githubusercontent.com/assets/1645099/5516160/74fd128e-888d-11e4-872e-6f7bb2b616a4.png)
![settings-2-tl_galerie](https://cloud.githubusercontent.com/assets/1645099/5516159/74fcfaec-888d-11e4-8729-6013803b9135.png)
![settings-3-tl_galerie](https://cloud.githubusercontent.com/assets/1645099/5516158/74fc3fc6-888d-11e4-9301-83a90340ed20.png)
![settings-4-tl_galerie_pictures](https://cloud.githubusercontent.com/assets/1645099/5516157/74fb8bee-888d-11e4-9520-c1a8691a6cef.png)

**Comment by lionel-m** [comment]
I deleted the permissions check for images. Anyway, we can not restrict the actions for the creation, deletion, etc. of images.
Currently, we can restrict the creation and deletion of a gallery and also remove fields if needed.
