### ISSUE TITLE
PHP7 issue

### ISSUE THREAD

**Issue by planepix** [lionel-m/galerie#18]
Hi Lionel,

is there a possibility to get your extension PHP7-ready?

Guess some user get this error message when try to use it with PHP7 and Contao 3.5.21:
`Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/....../system/modules/core/library/Contao/String.php on line 28`

Issue postet in german forum:
https://community.contao.org/de/showthread.php?65287-Hilfe-quot-Galeria-quot-Fatal-Error-Cannot-use-String-as-class-name-as-it-is-reserved

Thank you in advance
Thomas

**Comment by lionel-m** [comment]
I'll see that

**Comment by lionel-m** [comment]
Resolved in 12c442747d02cb0dfbdf05b833912ee114bd491a

New version [2.4.1](https://github.com/lionel-m/galerie/releases/tag/2.4.1)

Thanks @planepix
