### ISSUE TITLE
actual Version 2.4.1 doesn't work with the primary themes from galleria.io

### ISSUE THREAD

**Issue by harley-rider** [lionel-m/galerie#19]
I get the Error 'Fatal error: This version of theme requires Galleria version 1.5 or later' in contao.
I've seen that in the actual version 2.4.1 is the galleria-1.4.5.js' included.
Can you please make a version with the actual Modul 'galleria-1.5.6.js' ?
thanks

**Comment by lionel-m** [comment]
Yes I will update the extension

**Comment by lionel-m** [comment]
The new version is published and available in the extension repository. Please could you test it and keep me posted thx.

**Comment by harley-rider** [comment]
Thanks for the update
I made it on the demosite (you know the URL)
It works with the classic Theme.

**Comment by lionel-m** [comment]
Ok great !
